language: rust
cache: cargo
matrix:
  include:
    # Stable channel.
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
# some tests are failing on windows target:
#   thread 'tests::file_hash_bytes_processed_event_handler_defined' panicked at 'Failed to remove test directory.: Os { code: 145, kind: Other, message: "The directory is not empty." }', src\libcore\result.rs:1084:5
#    - os: windows
#      rust: stable
#      env: TARGET=x86_64-pc-windows-msvc

addons:
  apt:
    packages:
      # needed to build deb packages
      - fakeroot

env:
  global:
    # Default target on travis-ci.
    # Used as conditional check in the install stage
    - HOST=x86_64-unknown-linux-gnu
    # Used on the deployment script
    - PROJECT_NAME=hshchk

install:
  # prevent target re-add error from rustup
  - if [[ $TRAVIS_OS_NAME = linux && $HOST != $TARGET ]]; then rustup target add $TARGET; fi

script:
  # Incorporate TARGET env var to the build and test process
  - cargo build --target $TARGET --verbose
  - cargo test --target $TARGET --verbose

before_deploy:
  - bash ci/before_deploy.bash

deploy:
  provider: releases
  # NOTE updating the `api_key.secure`
  # - go to: https://github.com/settings/tokens/new
  # - generate new token using `public_repo` scope
  # - encrypt it using: `travis encrypt API_KEY_HERE`
  # - paste the output below
  api_key:
    secure: Ee4dLjmQXx9SCLW/lY+L+FxF4sMW9LVkBvLkO7Z79XrEFRRBK4XoODfkUrFQeDj5thpWh7kFFmBiaRFWs5uvJka3HMb2jdmI8WCCtA9rahbRjuKBMkENpOT2YuYpgorEENZnEl4aPLtkvcldnqrn5y6rhnptPQYcoXNYVzLk3EmAc3tHSeJDJ+3goUxzUOTPZqPQ90LvVFA0DP8s97gAJoYAxnUKX1eL3Xwsb5SGdQqQz+39ukfVX0suXvF+6DKh9UGUyC7fdeM4pseLqYhUv2ec0+M15Y7bQpger/WiqAWxqlW68wcUcBIjcR46RBiIh9nORIwmwjZiqPoPhZ4jW8GRzhCT3bo6zSrMkL4pUhI6Ws/YhLe7FyFDulFxyYeGeVkquv2Te9jle91rsjaGB8lv5R/NOYydVdhX1NeT12jyZpbtDTM5pkH24WvtCQ8BMYD7VuId9Cjp1dVdFeQh7YdL2IvrW+TV4x4TNQv6zEb/CrKKar0Qq9sayEie4IcPr8fnw9u7sQMXtbM7QsvwehSlXUAXxEbzhvjH14HMTg3B9plqL6dJaJYqZFN7m9QZZ/hmaFn6fu2eCvFsBycOYNaKve012eVR5K9/A2OfbqfKaT07GlltpcfUUV+Hhh1XjcS+9bHS8aR6G74wAGknSp8IVHfThHGYfGVvLbbQddw=
  # for uploading multiple files
  file_glob: true
  # NOTE explanation on each env variable
  # - PROJECT_NAME: name of the project, set on the `env.global` above
  # - TRAVIS_TAG: tag name that the build is being deployed for, usually the version number
  # - TARGET: target triple of the build
  file:
    - $PROJECT_NAME-$TRAVIS_TAG-$TARGET.*
    - $PROJECT_NAME*.deb
  # don't delete artifacts from previous stage
  skip_cleanup: true
  draft: true
  on:
    # deploy only if we push a tag
    tags: true
    # deploy only on stable channel that has TARGET env variable sets
    condition: $TRAVIS_RUST_VERSION = stable && $TARGET != "x86_64-pc-windows-msvc"

notifications:
  email:
    on_success: never
