language: rust
cache: cargo
matrix:
  include:
  - os: linux
    rust: stable
    env: TARGET=x86_64-unknown-linux-gnu
  - os: linux
    rust: stable
    env: TARGET=x86_64-unknown-linux-musl
  - os: osx
    rust: stable
    env: TARGET=x86_64-apple-darwin
addons:
  apt:
    packages:
      - fakeroot
env:
  global:
    - HOST=x86_64-unknown-linux-gnu
    - PROJECT_NAME=hshchk
    - secure: KODZZX7oleteUjn+DEIAqpR8kROaiCITiAEc03QDI7QAXsTMKTIFf8puyQhkMDXMYVCLNTWeOJIPlE8+hsW9vdirIElu2VqNhExxmiSVa/dEgWhegoYOcB0Ln2sZ3ATFK3DxTL9H7aqUHZyHj3NFQBE+vPfxIdbu0Mnur3xfomjyknpcEY7t2W6R45eML/qrS6xY4HrEcUiqLYxmh5UO/Rvb7TkT+5octzc9Rr7AkgjYX9yJv04t4LEba+gslUN7b3GzRdiuZqyeQOv9FWLS4mHQrtJF1ywICM7Yu13EKKCrotnSwoot44IUeLDuhuwUUZCrOpfmFKDHxn9359+AAdMLVyNoTnvKyris3UbWpAraqSgU6kuVvyXwS4Od5SG/aNKOBZTN3q2Y78+SKrONP5FrOzdzfXRdXagMYNtG+LnD/Y2/EdP334li+oZjnCCy5ysaH3XQmn/jNvrddpQ5CWRxSPwg2KM3Cnpt0SsfFXTIcq3Py0AW+JNVuzzy60HsQ5cw1gFTrXeCK3qrHYDx1Ifj7+e0F6gNrej65O97BAk67pUxHIudg3wh99MF3/9Owgd5OmZ2bgZGMexJtOYWzEuEksQ6a0yOTrRsw3uw5qMvgyfODp3HH1WNX6/DZOlTrG6dO+uEKit8f9dHZGAIthZJ/aJE+50Vp/NhCX2aE+E=
install:
  - if [[ $TRAVIS_OS_NAME = linux && $HOST != $TARGET ]]; then rustup target add $TARGET;
    fi
script:
  - cargo build --target $TARGET --verbose
  - cargo test --target $TARGET --verbose
before_deploy:
  - bash ci/before_deploy.bash
deploy:
  provider: releases
  api_key:
    secure: mjKaIUhrbx7/Pqbbk6xWSStocdKF7RWVmU+jb11dyRFfff+hGIm1woFUY4FD+NyQJ5j8gL8puW1zmeN48qhLdnos8Hl6iEsNMeydXVuVyGv4vRxH2VRvBz1EbyofPG7ilTjs6IPPYM9iZ6aAx3ZSAQ5m/tJ1ytbwwHOML1KclOWA97I/tG61pGMhZKLAkKPnbdRFvwnn8LtZoUuVpKC9hCW4ZS2trX6Yk6/QYtU5nEyqPmHMRC7EjpMR34F7kR+z8Z98bAwu2P2nYLVxSt/J1YMAcQeKDnBch7fcv9NA4ivXlAlmQZud0BIFAprblJ1E+WkGr05JJ1Z6DXDeH2KwgJzV+bL7gKOowmMgVFENdIg1KlMe5umf6Lbq3tcIb1AcxWbOfPZ5WE58uNgSSz4/S9WnXJyQk3YMHZI3ciW1CfGaSwJW/IUP4ch1jmNp7X0LK4I4t9qbMqVFLz6wupTeZnPSNbAfRQKkelQbHJMM8l1MIFwH39kq5c0rAaiZO+0r3UY1ryy6H3tVXFpUuAse432cXeoUcX7yiFIbwfRZ5YR+XGiVFI/6ZuK+Y4o5I+0ItqqP7tOdSNafWiKmh0flRBptX4/7lV4rQLpnSABOhUBRsl7+mcuC+38stsjev+Ddc5yallubLzARq5Y8cys9OV4biKAQoiENyZpOKyasDY4=
  file_glob: 'true'
  file:
    - $PROJECT_NAME-$TRAVIS_TAG-$TARGET.*
    - $PROJECT_NAME*.deb
  draft: 'true'
  on:
    repo: macote/hshchk
    condition: $TRAVIS_RUST_VERSION = stable && $TARGET != "x86_64-pc-windows-msvc"
  skip_cleanup: 'true'
notifications:
  email:
    on_success: never
